spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        show_sql: true
#        format_sql: true

  sql:
    init:
      schema-locations: classpath:h2test/schema.sql
      data-locations: classpath:h2test/data.sql

#logging:
#  level:
#    org.hibernate.orm.jdbc.bind: trace
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE